name: vint

on:
  pull_request:
    branches:
      - main

jobs:
  vint:
    name: vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Vint Action
        uses: ludvighz/vint-action@v1
        with:
          path: $(ls **/*.py)
